In [125]:
import numpy as np
import matplotlib.pyplot as plt
from random import randint
import random
import cmath
%matplotlib widget

np.random.seed()

def jastrow(x,g,v):
    s = 0
    L = int(len(x)/2)
    for i in range(L-1):
        s += g*x[i]*x[i+L] + v*(x[i]+x[i+L])*(x[i+1]+x[i+1+L])
    s += g*x[L-1]*x[2*L-1] + v*(x[L-1]+x[2*L-1])*(x[0]+x[L-1])
    return -s

def ground(n):
    L = int(8*n+4)
    x = np.zeros(2*L,dtype=int)
    for i in range(int(L/2)):
        x[2*i+1] = 1
        x[2*(i+int(L/2))] = 1
    return x

def monte(x, L, g, v):
    random = randint(0, 1)*L
    swap = [randint(0, L-1) for i in range(0,2)]
    x_new = x[:]
    if x_new[swap[0]+random]!=x_new[swap[1]+random]:
        x_new[swap[0]+random], x_new[swap[1]+random] = x_new[swap[1]+random], x_new[swap[0]+random]
        old_jastr = jastrow(x, g, v)
        new_jastr = jastrow(x_new,g,v)
        index_old = []
        index_new = []
        for i in range(2*L):
            if x[i] == 1:
                index_old.append(i)
            if x_new[i] == 1:
                index_new.append(i)
        old_U = U[index_old]
        new_U = U[index_new]
        prob = (np.abs(np.linalg.det(new_U))/np.abs(np.linalg.det(old_U))*np.exp(new_jastr-old_jastr))**2
        print(np.linalg.det(new_U))
        print(np.linalg.det(old_U))
        print(np.exp(new_jastr-old_jastr))
        acceptance = min(1,prob)
        if acceptance == 1:
            return x_new
        else:
            y = np.random.uniform(0, 1)
            if y<=acceptance:
                return x_new
    return x

n = 0
L = int(8*n+4)
H0 = np.zeros((2*L, 2*L))
for i in range(L):
    for k in range(L):
        if k == i+1 or k == i-1:
            H0[i][k]=-1
            H0[i+L][k+L]=-1
H0[0][L-1]=-1
H0[L-1][0]=-1
H0[L][2*L-1]=-1
H0[2*L-1][L]=-1

U0 = np.linalg.eigh(H0)[1]
U = U0[:,[np.arange(0,int(L/2))]]
print(U)
x = ground(n)
density_A = 0
Density_A = []
density_B = 0
Density_B = []
for i in range(1000):
    x = monte(x,L,10,2)
    for j in range(int(L/2)):
        density_A+=2/L*(x[int(2*j)]+x[int(2*j+L)])
        Density_A.append(density_A/(i+1))
        density_B+=2/L*(x[int(2*j+1)]+x[int(2*j+1+L)])
        Density_B.append(density_B/(i+1))
plt.figure()      
plt.plot(Density_A)
plt.plot(Density_B)
plt.show()

    

[[[0.5 0. ]]

 [[0.5 0. ]]

 [[0.5 0. ]]

 [[0.5 0. ]]

 [[0.  0.5]]

 [[0.  0.5]]

 [[0.  0.5]]

 [[0.  0.5]]]
[[[0.5 0. ]]

 [[0.5 0. ]]

 [[0.  0.5]]

 [[0.  0.5]]]
[[[0.5 0. ]]

 [[0.5 0. ]]

 [[0.  0.5]]

 [[0.  0.5]]]


LinAlgError: Last 2 dimensions of the array must be square

(6.123233995736766e-17+1j)