In [60]:
import numpy as np
import matplotlib.pyplot as plt
from random import randint
np.random.seed()

def jastrow(x,g,v):
    s = 0
    for i in range(int(len(x)/2)):
        s+= (-g) * abs(x[2*i]*x[2*i+1])
        if i!= (len(x)/2-1):
            s+= (-v) * (abs(x[2*i])+abs(x[2*i+1]))*(abs(x[2*i+2])+abs(x[2*i+3]))
    return s

    
def monte(x,L):
    random = randint(0, 1)*L
    swap_random_1 = randint(0, int(L/4)-1)
    swap_random_2 = randint(int(L/4), int(3*L/4)-1)
    a = x[swap_random_1+int(random)]
    x[swap_random_1+int(random)] = x[swap_random_2+int(random)]
    x[swap_random_2+int(random)] = a
    
    return x
        

def ground(n):
    L = int(8*n+4)
    x = np.zeros(2*L,dtype=int)
    for i in range(int(L/2)):
        x[2*i+1] = 1
        x[2*(i+int(L/2))+1] = 1
    U = np.zeros((2*L, L),dtype=np.complex_)
    print(x)
    for i in range(2*L):
        for k in range(L):
            I = (i + i % L)
            N = (k + k % (L/2)) - 1
            U[i,k] = np.exp(-complex(0,1)*2*np.pi/L*I*N)
            print(np.exp(-complex(0,1)*2*np.pi/L*I*N))
    return U

X = [1,2,3,4,5,6,7,8,7,8,1,2,3,4,5,6]
y=[1,2,3,4,5,6,7,8,7,8,1,2,3,4,5,6]
x_new = monte(X,8)
print (np.array(x_new)-np.array(y))



[ 0  0  0  0  0  0  0  0  0 -6  0  6  0  0  0  0]


In [169]:
import numpy as np
import matplotlib.pyplot as plt
from random import randint
np.random.seed()

def ground(n):
    L = int(8*n+4)
    x = np.zeros(2*L,dtype=int)
    for i in range(int(L/2)):
        x[2*i+1] = 1
        x[2*(i+int(L/2))+1] = 1
    U = np.zeros((2*L, L),dtype=np.complex_)
    for i in range(2*L):
        for k in range(L):
            I = (i + i % L)
            N = (k + k % (L/2)) - 1
            U[i,k] = np.exp(-complex(0,1)*2*np.pi/L*I*N)
    return x

def monte(x, L):
    random = randint(0, 1)*L
    swap = [randint(0, L-1) for i in range(0,2)]
    x_new = x[:]
    x_new[swap[0]+random], x_new[swap[1]+random] = x_new[swap[1]+random], x_new[swap[0]+random]
    return x_new
    
    
x = ground(1)
print(x)
y = monte(x,12)
print(y)

[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
[0 1 0 1 0 1 0 1 0 1 0 1 1 1 0 1 0 1 0 1 0 0 0 1]


In [155]:
[randint(0, int(12)-1) for i in range(0,2)]


[4, 10]